name: unionportal
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  http: ^0.12.1
  flutter_bloc: ^6.0.0
  flutter_swiper: ^1.1.6
  intl: ^0.16.1
  flutter_widget_from_html: ^0.3.3+3 #^0.4.3
  share: ^0.6.4
  flutter_spinkit: ^4.1.2+1
  image_picker: ^0.6.7+4 #^0.6.6+1
  toast: ^0.1.5
  flutter_launcher_icons: ^0.8.0
  flutter_cupertino_date_picker: ^1.0.12
  auto_size_text: ^2.1.0
  flushbar: ^1.10.4
  flutter_barcode_scanner: ^1.0.1
  flutter_staggered_grid_view: ^0.3.0
  firebase_messaging: ^7.0.0
  connectivity: ^2.0.2
  #barcode_scan: ^2.0.1

  # New added dependencies
  flutter_svg: ^0.19.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/Fonts/Cairo-Bold.ttf
        - asset: assets/Fonts/Cairo-ExtraLight.ttf
        - asset: assets/Fonts/Cairo-Light.ttf
        - asset: assets/Fonts/Cairo-Regular.ttf
        - asset: assets/Fonts/Cairo-SemiBold.ttf

  assets:
    - assets/images/navbaricon.png
    - assets/images/fontsize.png
    - assets/images/navheaderuser.png
    - assets/images/barcode.png
    - assets/images/report_item.png
    - assets/images/complain.png
    - assets/images/search_drawer.png
    - assets/images/cart.png
    - assets/images/jamianews.png
    - assets/images/offers.png
    - assets/images/socialnews.png
    - assets/images/finreports.png
    - assets/images/board.png
    - assets/images/barcodeicon.png
    - assets/images/scan.png
    - assets/images/logo.png
    - assets/icons/